[package]
name = "ckb-onion"
version = "1.2.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
license = "MIT"
description = "Onion service module"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"
rust-version = "1.95.0"

[dependencies]
data-encoding.workspace = true
ed25519-dalek = { workspace = true, features = ["hazmat"] }
hmac.workspace = true
hex.workspace = true
rand.workspace = true
sha2.workspace = true
tiny-keccak = { workspace = true, features = ["sha3"] }
tokio = { workspace = true, features = [ "full", "macros" ]}
ckb-error.workspace = true
ckb-async-runtime.workspace = true
ckb-logger.workspace = true
ckb-stop-handler.workspace = true
ckb-network.workspace = true
thiserror.workspace = true
strum.workspace = true

[dev-dependencies]
ckb-network.workspace = true
