# NOTE: This file is generated by `./scripts/render_main_tf.sh`.
#       Please Read `./scripts/render_main_tf.sh` for more information.

provider "aws" {
    region = "us-east-2"
    alias  = "us-east-2"
    access_key = "${var.access_key}"
    secret_key = "${var.secret_key}"
}

data "aws_ami" "ubuntu-us-east-2" {
  provider = aws.us-east-2
  most_recent = true
  owners      = ["099720109477"] # Canonical
  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*"]
  }
}

resource "aws_key_pair" "key-us-east-2" {
  provider      = aws.us-east-2
  key_name   = "${var.prefix}"
  public_key = file(var.public_key_path)
}

resource "aws_instance" "instance-us-east-2" {
  provider = aws.us-east-2
  ami           = data.aws_ami.ubuntu-us-east-2.id
  key_name      = aws_key_pair.key-us-east-2.id
  instance_type = "${var.instance_type}"
  root_block_device {
    volume_size = "60"
  }
  tags = {
    Name  = "${var.prefix}"
  }

  provisioner "remote-exec" {
    inline = [
      "while [ ! -f /var/lib/cloud/instance/boot-finished ]; do echo 'Waiting for cloud-init...'; sleep 1; done",
    ]

    connection {
        type        = "ssh"
        host        = aws_instance.instance-us-east-2.public_ip
        user        = var.username
        private_key = file(var.private_key_path)
    }
  }
}

output "ansible-hosts-us-east-2" {
  value = <<EOF

us-east-2:
  hosts:
    instance-us-east-2:
      ansible_host: ${aws_instance.instance-us-east-2.public_ip}
      instance_type: ${aws_instance.instance-us-east-2.instance_type}
      region: us-east-2
      prefix: ${var.prefix}
      ansible_user: ${var.username}
EOF
}
